pagename: "/kontent/settings"
attributes: 
    kategory:class: "setting"
    kategory:version: "1"
    kontent:class: "kategory"
    kontent:title: "Kontent settings"
    kontent:version: "1"
    rev:author: "/users/contributors"
    rev:log: "Initial page creation during import."
